### ISSUE TITLE
TrackIR software v5.3

### ISSUE THREAD

**Issue by s707** [uglyDwarf/linuxtrack#107]
Hi I have downloaded Linuxtrack  0.99.12 dmg for mac which supports up to TrackIR 5.2 to get extract the firmware for the TrackIR; however, TrackIR just updated their software to 5.3 (and I can't find any older versions). Any suggestions?

Thanks a lot!

I noticed that there is a 0.99.13 but I wasn't able to compile it to a dmg (beyond my skill)

**Comment by s707** [comment]
Think that I got it worked out. Downloaded v5.3 and unpacked on a PC, moved to my Mac and then used the 'unpacked option'. Seems to work ok. Thanks for the great software!

**Comment by uglyDwarf** [comment]
Hi,
I'm glad you made it work...

As for 0.99.13, I'm still polishing few rough edges in the build process, but it should be ready in a few days time...

Kind regards,

Michal

**Comment by uglyDwarf** [comment]
Hi,
the new version 0.99.15 should be able to download/extract the TrackIR firmware again...

The story is this: NP for some reason removed all older software releases - that was the reason why Linuxtrack was not able to download them again. Also the new installer requires at minimum Windows Vista, while Wine uses XP as default. Both problems are fixed now.

I'm closing this issue now, should you encounter any other problem, please let me know.

Kind regards,

Michal
