### ISSUE TITLE
Cant resolve error following relocation of LinuxTrack (why did I meddle???!?)

### ISSUE THREAD

**Issue by bignphil** [uglyDwarf/linuxtrack#119]
Hope you can help. I'm on iMac27 and have trackIR5 with pro clip. I am trying to use this set up for Xplane 10.

After hours of searching forums and generally getting fed up (I'm not that technical), I eventually came across linuxtrack, and after another hour or so got everything working fabulously.

Then - like a muppet - I decided to drag and drop the linuxtrack directory from one location to another (to make it tidier). Why oh why did I do that???!!

Now, when starting Xplane I get message saying:
"Linuxtrack was removed or relocated. If you relocated it, run ltr_gui from the new location, save preferences and try again."

I have done this to no avail. I have literally removed it and re-installed, followed all the guidance regarding setup, re-done the xplane plugin and still, same error in X-plane.

I should say, that in the linux track ltr_gui, I can use 3d view and cameraview and it moves and works with no problems at all.

Short of uninstalling Xplane and linuxtrack, then re-installing everything again, I'm at a loss and would appreciate any help. 

Perhaps this post will help others too.

**Comment by uglyDwarf** [comment]
Hello,
the only thing you need to do is to open the ltr_gui from the location you moved it to and click save  preferences; then close it again and try the X-Plane - the plugin should work again...
If it doesn't help, just let me know and I'll try and help you...
Kind regards,
Michal

**Comment by bignphil** [comment]
Thankyou Michal. I had tried that, but tried it again and it still didn't work. However - inadvertently - I did solve the issue. 

It seems that ltr_gui needs to be opened, then Xplane opened, then ltr_gui closed (in that order).

I had been trying to open then close ltr_gui then Open Xplane, or open Xplane, then open ltr_gui, then close ltr_gui - and its likely that this order was the cause of the issue.

Hope this helps someone else.

Anyway - thanks for your help - being able to use LinuxTrack makes such a difference to my enjoyment of the game.

Thumbs up devs. :)

**Comment by Jasperschn** [comment]
Same problem here. I installed the linuxtrack then set up the track ir. Then installed the xplane plugin and it worked like a charm. But after moving the folder with the ltr_gui file to his final destination i got the same message: "Linuxtrack was removed or relocated. If you relocated it, run ltr_gui from the new location, save preferences and try again."

So i closed xplane and run the ltr_gui and saved. Closed the ltr_gui and opened xplane. I got the same message again. 

I am gonna try bignphil his solution tonight and let you guys know if I have any results.

**Comment by Jasperschn** [comment]
Oke i tried the same solution as bignphil and it worked!
So:
-Run the ltr_gui
-Run xplane
-Close the ltr_gui
-Close xplane

And the next time you open xplane you dont get the message 'linuxtrack is moved or deleted' anymore.
I am using the macOS Sierra, with xplane 10.51 and a trackIR with a serienumber > 300000.
With linuxtrack-0.99.17_tir5v3.dmg

**Comment by uglyDwarf** [comment]
Hi,
that is strange, it shouldn't work like that...
Unfortunately I'm at a point where I don't have X-Plane installed at all, so I can't try that myself...
Hopefully next month I'm getting a new Mac, so as soon as I can I'll try to track that problem down and see if I can fix it...
Kind regards,
Michal

**Comment by bignphil** [comment]
Thanks Michal

**Comment by uglyDwarf** [comment]
Hi,
it looks I was able to reproduce the problem at last...
It seems that this problems appear only if the ltr_gui is started from inside the .dmg; if the ltr_gui is dragged to say Desktop, or Applications folder, started, preferences saved and quit, then it seems that everything works just fine...
Will try to document the problem and solution...
Kind regards,
Michal
PS. The feature responsible for this is called Gatekeeper Path Randomization...

**Comment by e4z9** [comment]
I had the same issue, with the same solution, but I did not run ltr_gui from the `.dmg`, but copied all content to a folder first.

**Comment by e4z9** [comment]
Ok, ignore me. For some reason the quarantine flag was never clearer, even after copying the contents of the `.dmg` and running `ltr_gui.app`.

`xattr -d com.apple.quarantine ~/Applications/LinuxTrack/ltr_gui.app`

fixed the issue.
