### ISSUE TITLE
Linuxtrack lacking permissions for TrackIR in Fedora 25

### ISSUE THREAD

**Issue by mklhnssn** [uglyDwarf/linuxtrack#122]
Not to be confused with Issue #70:
I compiled linuxtrack from source according to the RPM-based distro instructions. I don't exactly know why, but at the end of the configure script run, TrackIR support was "no"; perhaps that's a clue.

I can see that the udev rule for my TrackIR is being read and executed, since the device node actually has the permissions demanded by the rule ("0666").
The symptoms are very similar, though: When I run ltr_gui, I am faced with a dialog stating that 
```
TrackIR device was found, but you don't have permissions to access it.
 Please install the file 99-TIR.rules to the udev rules directory (...)
```
My CH stick and pedals show up as selectable devices in the linuxtrack gui, but the TrackIR is nowhere to be found.

Running ltr_gui after setting LIBUSB_DEBUG=3 doesn't present any output to my terminal but gives me the same error dialog. Journalctl presents a single line which doesn't seem to be relevant to the issue:
```
org.gnome.Shell.desktop[1726]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x1a0000b specified for 0x1a00038 (TrackIR pe).
```

Any tips for further troubleshooting?

**Comment by uglyDwarf** [comment]
Hi,
the TrackIR support is based on the availability of libusb1 and libz... If you install development packages of those libraries, it should compile just fine...
Kind regards,
Michal

**Comment by mklhnssn** [comment]
Thank you, that worked perfectly. Case closed. :)
