### ISSUE TITLE
How to actually run linuxtrack?

### ISSUE THREAD

**Issue by OZ1SEJ** [uglyDwarf/linuxtrack#127]
I've done installation steps 1-4 as outlined on https://github.com/uglyDwarf/linuxtrack/blob/master/INSTALL. In the Wiki, I can find descriptions on how to use the program, but how do I start the program? I can't find that info anywhere...?

**Comment by uglyDwarf** [comment]
Hello,
first of all, I'm sorry for the confusion - I'll have to go through the docs and see what is still relevant and what is not...
Actually all you have to do (unless you want to compile it yourself), is to download the universal package ( https://github.com/uglyDwarf/linuxtrack/wiki/Downloads ), unpack it to /opt (unzip first, then unpack the .tar.bz2 archive), optionally add /opt/linuxtrack-0.99.18/bin to your path and run ltr_gui that resides in the above said bin directory...
Let me know if you have any problems...
Kind regards,
Michal

**Comment by OZ1SEJ** [comment]
Thanks! That sounds easier :-) So now I downloaded that file, extracted and run it, and now I'm getting this:

![skaermbillede fra 2017-01-28 23-51-19](https://cloud.githubusercontent.com/assets/2393164/22400416/e25ac502-e5b4-11e6-9c3f-f99c26277bc7.png)

I have no idea what that means. I also get a warning because I don't have Wine, but I guess it's okay since it's only a warning...?

**Comment by uglyDwarf** [comment]
Hello,
the steps necessary to get the TrackIR running should be in the help (ltr_gui, button in the lower left corner, if my memory serves me right) - technically you need to copy the udev rule file you find in /opt/linuxtrack.../share/linuxtrack (writing from the top of my head, but you should find it) to a directory /lib/udev/rules.d (you'll need sudo for that)...
As for wine, depending on the TrackIR version, you might need it to extract the firmware; place the udev rule, re-plug the TrackIR (or restart the system) and run ltr_gui - if the firmware is necessary, you'll see there a button to get it. And last, but not least, NP seem to changed the location of their package, so you might need to download it manually from their site (the extraction can be performed by ltr_gui).
Kind regards,
Michal

**Comment by OZ1SEJ** [comment]
Ah - everything works perfectly now - thank you!

I had the same problem as some others - the files couldn't be extracted from the installer from NaturalPoint. So I just installed it on a Windows machine and copied the files to my Ubuntu box.

Is Wine needed for anything but extracting that file? Could I remove it now, or does LinuxTrack actively use it when running?

Best regards,
Steen
