### ISSUE TITLE
Program freezes when stopping the camera testing

### ISSUE THREAD

**Issue by T10a** [uglyDwarf/linuxtrack#130]
Hi,
I'm trying to test out my webcam and headtracking with this software. However, the 3D display doesn't move, the camera display doesn't show the camera output. The FPS is stuck at 0 while testing, and finally the software fails to respond after pressing the stop button on the Tracking window.
Webcam: Playstation 3 Eye. (unmodified, trying face tracking)
Linux distro: Arch Linux
Display drivers: AMDGPU
Linuxtrack version: 0.99.18

Log I got from running ltr_gui in the terminal:
`Found device 0`
`libpng warning: iCCP: known incorrect sRGB profile`

Pastebin of the Linuxtrack log: https://pastebin.com/85BgZetk

Weirdly enough, the file it is requesting (libft.so.0) is a link to another file (libft.so.0.0.0)

**Comment by uglyDwarf** [comment]
Hello,
the problem seems to be missing libopencv_core.so.2.3; it seems the 0.99.18 encountered a problem during the building... Please try the 0.99.17 instead?
Kind regards,
Michal

**Comment by T10a** [comment]
It works now. The motion during testing is jittery, and the camera is picking up objects in the background.
But I think that's a problem with my setup, not the software.
