### ISSUE TITLE
linuxtrack-0.99.18 fails to load on Debian Stretch

### ISSUE THREAD

**Issue by xpd259** [uglyDwarf/linuxtrack#132]
Hello, 
on the latest build, linuxtrack-0.99.18,  I'm getting an error when I try and launch ltr_gui
```
dthomas@thadeus ~/o/l/bin> ./ltr_gui 
./ltr_gui: error while loading shared libraries: libltr.so.0: cannot open shared object file: No such file or directory
```
I'm running Debian Testing (Stretch) amd64

regards

**Comment by uglyDwarf** [comment]
Hello,
the universal package must be installed in  /opt - like /opt/linuxtrack-0.99.18/bin/ltr_gui .
Kind regards,
Michal
