### ISSUE TITLE
pilotView kills Linux track... so it seems on XP11

### ISSUE THREAD

**Issue by xpd259** [uglyDwarf/linuxtrack#137]
Hello,

I just tried pilotview after seeing it in the code
file src/xlinuxtrack9.c , line333
and I discovered that it stopped the LinuxTrack plugin from working

This might explain the following bugs #131  and #110 

just thought I'd make you aware of this
I was using Fedora26(beta) XPlane11

regards
Dick

**Comment by uglyDwarf** [comment]
Hello Dick,
when the plugin finds that PilotView (or XCamera) is running, it stops trying to control the view in order not to clash with the other plugin. As far as the PilotView is concerned, you need to start the tracking (the button/key you assigned the ltr_run to), make sure you enabled it (in the plugin menu and also make sure you enabled external data sources in the PilotView config file - see https://github.com/uglyDwarf/linuxtrack/wiki/X-Plane10-Plugin-Setup , the PilotView plugin section).
Kind regards,
Michal
PS. To be honest, I didn't try the PilotView in the XP11 yet, but I do use it in XP9 and 10 and so far it works well... Will try it in the evening.

**Comment by xpd259** [comment]
Hello, 

Sorry It was really late/ early I will check myself again
I might have made a fubar, I was just hoping it would fix the problem for people 😺

**Comment by xpd259** [comment]
Hello again Michal,
it turns out the problem was with my config file.
good news it does work 👍
