### ISSUE TITLE
Controller.exe question

### ISSUE THREAD

**Issue by livernyc** [uglyDwarf/linuxtrack#146]
Quick question:

When I am running controller from within the wine prefix it list the key assigned to pausing and re-centering as "unknown".  When I issue the pause key combinations the pausing and starting operation seems to work based on the indicator lights on my Track IR.  I have not been able to get the tracking support in my IL2 1946 game to work yet.

**Comment by livernyc** [comment]
Just posting an update to my issue.  I was able to get my TrackIR 5 working with IL2 1946 4.12.x. under wine.  I wound up getting it working trough ltr_pipe not using the wine plug-in.  I think the last snag I hit was due to my client firewall being turned on I think.  

Very cool thank you so much for making this great tool that gives people an alternative to running windows and still enjoy this great game!!

**Comment by sigzegv** [comment]
How do you use ltr_pipe to send recenter and suspend actions ?
