### ISSUE TITLE
no linuxtrack-wine install dialog with 0.99.18 ?

### ISSUE THREAD

**Issue by sigzegv** [uglyDwarf/linuxtrack#150]
When I click the "install linuxtrack-wine support" button, it pops the trackir firmware install dialog.

Isn't this supposed to popup wine prefix selection dialog ?

(seems to also happen in 0.99.17 ??)

**Comment by uglyDwarf** [comment]
Hi,
first it needs to get some secret "poems" (used to discourage the unofficial usage of the interface) and other stuff from the NP's driver package  and only then it will ask you where you want to install the support to...
Kind regards,
Michal

**Comment by sigzegv** [comment]
well I think I have already managed to get those files, I have this in my ~/.config/linuxtrack/190121_133315/ (with a tir_firmware link to this folder) :
`TIRViews.dll
gamedata.txt
poem1.txt
poem2.txt
sn4.fw.gz
tir4.fw.gz
tir5.fw.gz
tir5v2.fw.gz`

I have extracted them from my trackir installation on windows (v5.4.2)

**Comment by uglyDwarf** [comment]
Then it should let you install the linuxtrack-wine stuff...

**Comment by sigzegv** [comment]
there should be an issue, I've tryed from a clean install, removed the .config/linuxtrack, restarted ltr_gui, I install firmware from unpacked installation (the installation from the setup exe always fails btw), it copies me the files I described previously, but I'm still unable to select a wine preview installation. There should be somethig wrong, or I may do something wrong ?

The ltr_gui alone works fine, I can track the clip.

**Comment by sigzegv** [comment]
Ok new step, I've ran manually the linuxtrack-wine.exe in my prefix and it seemed to work. Tester.exe works, game in the prefix works also with tracking. There's only the strange issue it tells me an mfc42u.dll is missing (I copied one manually), but it says the TIRViews.dll is also missing but it's not missing, it's there. BTW I don't know why it's required because trackir.exe works perfectly anyway. Any details on this @uglyDwarf ?

**Comment by uglyDwarf** [comment]
Hi,
I just tried after dumping all the setup and besides the fact, that I had to extract the TIR firmware manually (I have a change on that in the works) it worked like it should - asked to install the mfc42u.dll and then the dialogue to select the prefix...
Also after you install the firmware/mfc42u, then the Install Linuxtrack-Wine support button should directly launch the select prefix dialogue...
One thing I noticed - you seem to be missing the mfc42u.dll in the tir_firmware directory - from there it is linked to the wine prefix by the linuxtrack-wine.exe instaler.
As for why the newer versions do not work - not sure, but make sure to open the newly installed ltr_gui and save the preferences when you are done with the setup.
Maybe try closing everything linuxtrack related, delete all the logs in the /tmp and try starting the ltr_pipe to make sure the install works... Then try the wine tester and if that fails check the logs if there isn't anything strange (or pack them, attach here and I'll take a look)...
Kind regards,
Michal

**Comment by uglyDwarf** [comment]
Hi,
when you use the Install Linuxtrack-Wine support button, it should extract/install the mfc42u.dll...
Can you please list the contents of the Linuxtrack directory in the wine prefix? Also if you could copy here the exact text of the error message you get about the TIRViews, it might help...
Kind regards,
Michal
