### ISSUE TITLE
linuxtrack doesn't recognise opencv 4.x

### ISSUE THREAD

**Issue by CyberGuerro** [uglyDwarf/linuxtrack#169]
After I upgraded opencv to 4.1.2 from 3.4.1, when I rebuild linuxtrack, it tell me that opencv is not installed:

`checking for OPENCV... no
configure: error: Package requirements (opencv >= 2.0) were not met:

No package 'opencv' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables OPENCV_CFLAGS
and OPENCV_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
`
Could you verify this? Probably you have to upgrade "configuration requirement" procedure, I don't know, I'm not a linux package developer :-(

**Comment by CyberGuerro** [comment]
PLEASE @uglyDwarf  MERGE [This pull request](https://github.com/uglyDwarf/linuxtrack/pull/167)

**Comment by rfvizarra** [comment]
Hi CyberGuerrero,

have you tried applying the pull request (https://github.com/uglyDwarf/linuxtrack/pull/167) and then running aclocal, autoconf, automake and then configure before running make?

It applying the patch doesn't work try compiling the code in my fork https://github.com/rfvizarra/linuxtrack

I was able to compile it in Ubuntu 20.04 and Archlinux.

**Comment by CyberGuerro** [comment]
@rfvizarra, I've tried your changes by creating a package from the trunk in my distribution (Gentoo) and applying a patch file.
All works perfectly, but I would prefer that your pull request should be merged to the trunk instead of make me use a patch file for to the trunk release.
So I can close this issue in favour of [your pull request](https://github.com/uglyDwarf/linuxtrack/pull/167)
