### ISSUE TITLE
'Static assertion failed' error on WINE_DEFAULT_DEBUG_CHANNEL

### ISSUE THREAD

**Issue by calebaden** [uglyDwarf/linuxtrack#205]
I have been trying to get this working for a while and have tried multiple forks with no success. Every attempt at troubleshooting always circles around to this one error.

`FreeTrackClient_main.c:22:1: error: static assertion failed: "sizeof(\"FreeTrackClient\") <= sizeof(__wine_dbch_FreeTrackClient.name)"
   22 | WINE_DEFAULT_DEBUG_CHANNEL(FreeTrackClient);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~`

I'm using wine 9.7-1 from arch repo.

**Comment by calebaden** [comment]
Building with wine 8.21 fixed my issue and can then be run with wine 9.7 after.

**Comment by quinvirE** [comment]
Hey, how did you go about using a different wine version for the build?

**Comment by calebaden** [comment]
I downgraded my system wine to 8.21, then built linuxtrack, then upgraded back to latest version of wine after.
If you are on arch, you can use the 'downgrade' package, not sure about other distros.
