### ISSUE TITLE
Move mickey to a separate repository

### ISSUE THREAD

**Issue by trishume** [uglyDwarf/linuxtrack#97]
Hi, I'm interested in contributing to finish up your work on getting mickey to work on OSX. However, since mickey is bundled together with the same configure scripts as the rest of Linuxtrack it is unnecessarily difficult to build.

For example, I try to get the `.pro` file for mickey created, and can't configure since I'm missing dependencies for linuxtrack. I don't want to get the dependencies for and build everything since I already am happily using your build of linuxtrack for OSX.

May I suggest creating a separate Github repo for mickey and moving the source into there? It's a separate app so it makes sense. I already plan on extracting mickey from linuxtrack myself so that I can work on it, if you'd like I can give you a git repository created using [this process](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/) so it preserves the history, and you can just publish it under your username, and I can submit pull requests to it.

I'm aware that mickey uses some files from the rest of linuxtrack but I think duplicating those few files is an acceptable cost for cleaner separation.

If you don't want to do this then I'll just extract my changes as patches and PR them here, I won't be able to guarantee that they compile in the new location, but it will probably work.

@uglyDwarf

**Comment by uglyDwarf** [comment]
Hi,
I have no problem with that - I'll try to do the split during the weekend...
I'll let you know once it is done.

Kind regards,

Michal

**Comment by uglyDwarf** [comment]
Hi,
I have the thing separated, however I'm not able to do the split to a new repo - I always get to a state like this:

$ git push origin .
fatal: remote part of refspec is not a valid name in .
Unexpected end of command stream
$git status
On branch master
Your branch and 'origin/master' have diverged,
and have 37 and 305 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working directory clean

To be honest, I know svn relatively well, but I'm still learning the git, so I have absolutely no idea on what can I do to fix the thing... If you know what is wrong or how can I fix it, I'd be very grateful for any hints.

Thank you,

Michal

**Comment by sparker256** [comment]
Is this what you are looking for?

https://help.github.com/articles/creating-a-new-repository/

Bill

**Comment by trishume** [comment]
Indeed Bill is pointing you in the right direction.

What is going on is that when you ran the commands in that guide it turned your local version into what you want to put into the new mickey repository. Now all you have to do is make a new remote repository on Github (called `mickey`) using the first steps of the guide Bill linked, then change the remote

1. Use the Github web interface to create a new repository (named "mickey"), don't use the option to initialize it with something.
2. [Add a remote](https://help.github.com/articles/adding-a-remote/) to the local copy you ran the filter commands in for the new "mickey" repo. You'll have to delete the existing 'origin' (which points to the 'linuxtrack' repo remote, now wrong) using `git remote remove origin` first.
2. The `origin` remote for your local copy (that you just filtered) still points to the remote `linuxtrack` repo, you want to change that with something like `git remote set-url origin git@github.com:uglyDwarf/mickey.git`
2. Then run `git push origin` to push your local mickey repo to Github.

The reason you were getting the message you were getting was that it was trying to push to `uglyDwarf/linuxtrack` and thinking "this doesn't make sense, my local state isn't a new change, it's an entirely different history". You could have overridden that with `git push -f origin master` but then you would have replaced the files in this linuxtrack repo with the stuff that only includes mickey! :stuck_out_tongue:

Feel free to comment further if this doesn't work, I'm happy to help. Once you succeed expect PR(s) getting mickey to work on OSX. The repo will probably require some work getting builds set up so that you can compile the repo, I'm happy to help with that too if you don't have time.

**Comment by uglyDwarf** [comment]
Hello guys,
thank you for the suggestions... 

I was using this: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

but with the above result; when using this: http://stackoverflow.com/questions/359424/detach-subdirectory-into-separate-git-repository (community wiki answer), things went well (those 4 hours of sleep might have helped too ;) )...

Anyway, now the mickey repository is up, the thing compiles under Linux and it does even run (as far as I quickly tested).

Kind regards,

Michal

**Comment by trishume** [comment]
Thanks, looks great! I'll start work on OSX support soon.
