### ISSUE TITLE
How do I get it to work with X-Plane exactly?

### ISSUE THREAD

**Issue by MudassarBashir** [uglyDwarf/linuxtrack#98]
On Mac OS X Yosemite, it seems to be working fine, when I run ltr_gui I can see my Track IR 5 tracks my track clip and I even have the X-Plane plugin installed and I can see it in the plugin menu and I even set some keys to start, pause, and recenter within X-Plane but I don't see any tracking going on in X-Plane as I move my head. Even when I hit the assigned start key again and then again, I can see the lights on the track IR change color from orange to green so I know its responding to the keystroked from within X-Plane. Still, I can only see it track in the tracking window of the ltr_gui. I feel like I'm missing something simple. I even tried the PilotView plugin but it's 'enable track ir' and 'disable track ir' options are disabled. Please advise. Thank you.

**Comment by uglyDwarf** [comment]
Hello,
the "problem" is the PilotView plugin; in ltr_gui's help there is a topic of X-Plane's plugin and the last section concerns the PilotView.

In short, you need PilotView version 1.7 or higher, and you need to edit its config file to enable it to receive external data... And by the way, if you use any recent version of Linuxtrack, there is no need to reinstall the plugin again (it was meant for people using old Linuxtrack with plugin that didn't have that particular interface).

Hope it helps, if not, just let me know and I'll help you...

Kind regards,

Michal

**Comment by MudassarBashir** [comment]
Thanks, your advice worked perfectly on Track IR 5, X-Plane 10.36, Mac OS Yosemite.

**Comment by uglyDwarf** [comment]
I'm glad it works for you...
I'm going to close this issue then; should you encounter any more problems don't hesitate to file a new one or reopen this one...

Kind regards,

Michal
